'''
This file ontains multi langages constant tuples. The first element in
the tuple is the constant value for the english (default) langage. The
second is the french translation. Adding a langage is very simple: you
just add a supplementary element in the tuple.
'''
GB = 0
FR = 1
DEPOSIT_SHEET_HEADER_OWNER = ('OWNER', 'PROPR')
MERGED_SHEET_HEADER_EARNING_NEW_NAME = ('EARNING', 'REVENU')
DEPOSIT_YIELD_HEADER_DATE_FROM = ('FROM', 'DE')
DEPOSIT_YIELD_HEADER_DATE_TO = ('TO', 'A')
PROC_DEPWITHDR = ('DEP/WITHDR', 'DÉPOTS/RETRAITS')
PROC_DEP = ('DEPOSITS   /', 'DÉPÔTS  /')
PROC_WITHDR = ('  WITHDRAWALS', ' RETRAITS')
PROC_AMOUNT =  ('AMOUNT', 'MONTANT')
PROC_DATE_FROM_RATE = ('DEP RATE', 'VAL DAT DÉP')
PROC_CURRENT_RATE = ('CUR RATE', 'VAL ACT')
PROC_CAPITAL_GAIN = ('CAP GAIN', 'PLUS-VAL')
PROC_CAPITAL_SHORT = ('ONLY ', 'CAP ')
PROC_CAPITAL_GAIN_PERCENT = ('IN %', 'EN %')
PROC_YIELD = ('INTERESTS', 'INTÉRÊTS')
PROC_YIELD_SHORT = ('YLD ', 'INT ')
PROC_TOTAL_SHORT = 'TOT '
PROC_YIELD_DAYS = ('DAYS', ' JOURS')
PROC_INTEREST_SHORT = 'INT '
PROC_INTEREST = 'INT'
PROC_YIELD_AMT_PERCENT = ('IN %', 'EN %')
PROC_YEAR_YIELD_PERCENT = ('YRLY %', ' % ANNUEL')
PROC_PER_DAY = ('PER DAY', 'PAR JOUR')
PROC_PER_MONTH = ('PER MONTH', 'PAR MOIS')
PROC_PER_YEAR = ('PER YR', 'PAR AN')
PROC_IN = ('IN ', 'EN ')
PROC_RATE = ('RATE', 'COURS')
PROC_RATE_DEP_USD = 'DEP USD'
PROC_RATE_CURRENT_USD = ('CUR USD', 'ACT USD')
PROC_RATE_DEP_FIAT = 'DEP '
PROC_RATE_CURRENT_FIAT = ('CUR ', 'ACT ')

PROC_HELP_TXT_1 = ("deposit/withdrawal value at the date from rate", "valeur du dépôt/retrait au cours en vigueur à la date de cette transaction")
PROC_HELP_TXT_2 = ("value at the current rate of the yield generated by the deposit/withdrawal from date FROM to date TO", "valeur au taux actuel des intérêts générés par le montant déposé/retiré de la date DE à la date A")
PROC_HELP_TXT_3 = ("deposit/withdrawal + generated yield value FROM ... TO ... at the current rate", "valeur au taux actuel du dépôt/retrait auquel sont ajoutés les intérêts qu'il a généré DE ... A ...")
PROC_HELP_TXT_4 = ("capital gain, i.e. current rate deposit/withdrawal value minus deposit/withdrawal value at the date FROM rate", "plus-value ou moins-value du dépôt/retrait au cours actuel, à savoir VAL ACT - VAL DAT DEP")

LOCAL_TIME_ZONE = "Europe/Zurich"
DATE_FORMAT = "YYYY-MM-DD"
CRYPTO_FIAT_DATE_FROM_RATE = '{}/{}'
CRYPTO_FIAT_CURRENT_RATE = ' {}/{}'
PROC_DEP_RATE = ('DEP RATE', 'DAT DÉP')
PROC_CUR_RATE = ('CUR RATE', 'DAT ACT')